#pragma once

#if defined(ESP8266) || defined(ARDUINO_ARCH_ESP8266)
#error "ESP8266 is not supported in IoTSmartSysCore. Use an ESP32 target."
#endif

#ifndef IOTSMARTSYS_MINIMAL
#define IOTSMARTSYS_MINIMAL 0
#endif

#ifndef IOTSMARTSYS_PROVISIONING_ENABLED
#if IOTSMARTSYS_MINIMAL
#define IOTSMARTSYS_PROVISIONING_ENABLED 0
#else
#define IOTSMARTSYS_PROVISIONING_ENABLED 1
#endif
#endif

#ifndef IOTSMARTSYS_SENSORS_ENABLED
#if IOTSMARTSYS_MINIMAL
#define IOTSMARTSYS_SENSORS_ENABLED 0
#else
#define IOTSMARTSYS_SENSORS_ENABLED 1
#endif
#endif

#ifndef IOTSMARTSYS_OTA_ENABLED
#if IOTSMARTSYS_MINIMAL
#define IOTSMARTSYS_OTA_ENABLED 0
#else
#define IOTSMARTSYS_OTA_ENABLED 1
#endif
#endif

#ifndef IOTSMARTSYS_SETTINGS_FETCH_ENABLED
#if IOTSMARTSYS_MINIMAL
#define IOTSMARTSYS_SETTINGS_FETCH_ENABLED 0
#else
#define IOTSMARTSYS_SETTINGS_FETCH_ENABLED 1
#endif
#endif

#ifndef IOTSMARTSYS_REDACT_SECRETS
#if IOTSMARTSYS_MINIMAL
#define IOTSMARTSYS_REDACT_SECRETS 1
#else
#define IOTSMARTSYS_REDACT_SECRETS 0
#endif
#endif
