#pragma once

#define ESP32S3_BOARD_AI_LED_GREEN 43
#define ESP32S3_BOARD_AI_LED_BLUE 44
#define ESP32WROVER_LED_BLUE 13

#if defined(ESP32_S3_AI)
#define LED_BUILTIN ESP32S3_BOARD_AI_LED_BLUE
#define BOARD_LED_STATE_OFF HIGH
#define BOARD_LED_STATE_ON LOW
#elif defined(ESP32_WROVER)
#define LED_BUILTIN ESP32WROVER_LED_BLUE
#else

#endif